### PR TITLE
adding faucet abusers list

### PR DESCRIPTION
**Pull request by crokkon**
The following groups of accounts are controlled from a single entity each, all having ~14.9 SP delegated from `@steem`:

* `'steembidbots', 'postpromoters', 'sneaky-ninjas', 'uppit', 'sneaky-ninjaes', 'steembidbotes', 'hotbotes', 'jsshjo14', 'pushupes', 'upboaters', 'webhost', 'hostits', 'minnowfairys', 'whalebuilderes', 'postpromoteres', 'upgoaters', 'purevpn', 'excellindia', 'bdsians', 'batad', 'appreciators', 'upmes', 'upboateres', 'upgoateres', 'whalebuilders', 'apexd'`
  * voting pattern: 
vote_data
  * account creation dates
creation_data

* `'zinkotun', 'jacobcc', 'nyeemalay', 'fayfay', 'xeiomi', 'emmae', 'gyikoung', 'chopho', 'parlar', 'myintlwin', 'kokonaw', 'kyawlwin', 'nyeelay', 'roda', 'wart', 'citt', 'toethit', 'avaa', 'sinar', 'amay', 'fjfy', 'oliviao', 'soeooo', 'phopo', 'gofo', 'peterjone', 'lorpo', 'miam', 'mgtin699', 'gokar', 'myatwo', 'komyintphay', 'aungkyi', 'williamw', 'boee', 'esbellae', 'abigaila', 'ethane', 'tunlay', 'noahn', 'mgtint', 'thanna', 'jonko', 'jaydenj', 'nau', 'afoegyi', 'masonm', 'baybi', 'bornbay', 'mgtin', 'mgnyo', 'aidena', 'kitter', 'chloec', 'mghtay', 'madisonm', 'ninnoo', 'hownowko', 'sophias', 'oohlaing', 'zaungtu', 'yanyanchan', 'lwinhtay', 'umyintphayump', 'larnaylar', 'bonboe', 'soelay', 'danieldd', 'thulay', 'umyintpjay', 'afaytthay', 'nyiphae', 'michaell', 'cholay', 'emilyee', 'rota', 'aungthet', 'tharpu', 'kalaylay', 'mayyeethein', 'hoenoe', 'bosoe', 'nyinyioo'`
  * voting pattern
vote_data
  * account creation dates
creation_data

### CODE REVIEW

**Comment by AsherBH12345** [comment]
They've chosen misspelling bot and exchange names, and have a system going on here.  A good spot and something which looks like it could be fed into the 'irredeemables' to me.

**Comment by crokkon** [comment]
* adding bid-bot/exchange look-alike accounts: 462 accounts, all created between June 10th - 12th 2018
  * voting pattern
voting_times
  * `follow` operations pattern
follow_times

**Comment by HerbyW** [comment]
Same here: 

jilophu
fushcarbon
carolusmagnus
stb138
dernu
topfongo1
trucmipo
lopusazuli
cleversteem
qsedtylo
zartyo
sesamcrs
fertipo
jeanmarlo
velomasty
calipsuy
donaldducky

**Comment by roadscape** [comment]
Thank you @crokkon!

**Comment by crokkon** [comment]
Thank you @roadscape! Any chance to get the bid-bot/exchange look-alike accounts into condenser as well? 
https://github.com/steemit/condenser/pull/2914

**Pull request merged**
