### PR TITLE
Add SteemitDefenseLeague

### PR DESCRIPTION
**Pull request by themarkymark-steem**
Add @camillesteemer malicious flag network using Steemit Inc delegation

### CODE REVIEW

**Comment by roadscape** [comment]
Any documentation on how these names were found or links to evidence?

**Comment by RagePeanut** [comment]
By going on any of those profiles and clicking on [the justpaste.it link](https://justpaste.it/1jpbl), you can have a look at what they are doing. They are automatically flagging any account that happened to do something they don't like (flagging a post or interacting with someone on their list).

Those links may prove to be useful for understanding the situation at hand: 
- [How To Protect Yourself Against SteemitDefenceLeague](https://steemit.com/steemit/@johngreenfield/content-cop-how-to-tackle-the-abusers)
- [Are you also being downvoted by the 15 SP Steemit Doofus League accounts? Check This Out!](https://steemit.com/abuse/@anthonyadavisii/are-you-also-being-downvoted-by-the-15-sp-steemit-doofus-league-accounts-check-this-out)

The list of flagging bots created for the SteemitDefenceLeague gets bigger every week (it was only 4 accounts when it all started).

**Comment by livefreensmart** [comment]
This "League" is violating TOS 15.1.1 
> 15.1.1. Use of our Services in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying our Services, or that could damage, disable, overburden or impair the functioning of our Services in any manner;

@lovenfreedom Steemit Account

**Comment by TheLeonis** [comment]
Here is the list of known members:

@mybestnews
@camillesteemer
@steemittopfan
@a-alphasteem
@ilikesteemit
@besttopsteemer
@azobifly
@strumo
@a-cmsidl
@trollshunter
@a-steemdefleague
@oiepassive
@astipmonkey
@foodstreem
@aloader

This malicious troll also tries to post on SteemThat, pretending to be some sort of righteous crusader. The Eric dude that comments there seems to be a prominent figure there.

https://steemthat.com/the-steemit-defence-league-is-stopping-the-top-trolls-fake-abuse-reporters-and-i-have-decided-to-help-them/

Off-topic:
Personally, I think the folks at @steemthat (that's their Steemit handle) are not very bright as they seem be completely inept at telling which posts as genuine and which are plagiarized. Or they done this intentionally? Example, https://steemit.com/steem/@mohdaasim/the-heck-is-going-on-with-steem#@steemthat/re-mohdaasim-the-heck-is-going-on-with-steem-20180411t064747724z

**Comment by themarkymark-steem** [comment]
This all started when @camillesteemer was flagged by multiple people for spamming, she turned to promoting busy.org as her posts were not hidden there.  To take revenge, she swore to flag anyone who flagged her and anyone related to anyone who flagged her and is making 100 accounts to flag people using Steemit Inc delegation.  

You can find some details here: https://steemit.com/steem/@berniesanders/steemit-defence-league-is-a-fucking-joke and any of her posts.

Her main account @camillesteemer was flagged originally because she is a plagiarist.

**Comment by roadscape** [comment]
Thanks for the supporting notes, that's very useful to have documented here.

**Comment by themarkymark-steem** [comment]
I just ran the make file and that’s what it produced.

**Comment by jredbeard** [comment]
lgtm - thanks for your submission @themarkymark-steem

**Pull request merged**
