### PR TITLE
Add new pretty big voting farm (>800 accounts)

### PR DESCRIPTION
**Pull request by Flugschwein**
EDIT: I found a **lot** more - don't approve yet :)
This adds a voting farm which is farming a lot lately using 333 (or maybe a few more I didn't include in my list) to upvote their posts.
Voting behavior is pretty obvious:
vote_data

### CODE REVIEW

**Comment by roadscape** [comment]
Hey @Flugschwein - after other merges this one has conflicts. Could you bring it up to date? Thanks!

**Comment by Flugschwein** [comment]
I will as soon as I can!
Hopefully I get to it tomorrow ;-)

**Comment by Flugschwein** [comment]
I finished resolving the merge conflicts (after fighting with them in general for some time xD) now, @roadscape 
You should be able to merge this pull request now

**Comment by roadscape** [comment]
Awesome thanks @Flugschwein!

**Pull request merged**
